
services:
  bankofsaba.api:
    build:
      context: .
      dockerfile: BankofSaba.API/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
    depends_on:
    - sqlserver
    
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    networks:
    - productnetwork
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
       SA_PASSWORD: "Saba_1234"
       ACCEPT_EULA: "Y"
     
    ports:
     - "1433:1433"
    networks:
     - productnetwork


networks:
  productnetwork:


      
